COMMENT=		faraday adapter

DISTNAME=		faraday-net_http-3.0.2
PKGNAME=		faraday-net-http-3.0.2
CATEGORIES=		devel

MAINTAINER=	i	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
