COMMENT=		faraday adapter

V=			3.0.2
DISTNAME=		faraday-net_http-${V}
PKGNAME=		faraday-net-http-${V}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/lostisland/faraday-net_http

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
