COMMENT=		strptime strftime engine

DISTNAME=		strptime-0.2.5
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-2-Clause
PERMIT_PACKAGE=		Yes

WANTLIB+=		c m

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
