COMMENT=		Ruby API to Nexpose vulnerability

DISTNAME=		nexpose-7.3.0
CATEGORIES=		security

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
