COMMENT=		IANA Time zone database

DISTNAME=		tzinfo-data-1.2023.3
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			sysutils/ruby-tzinfo

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
