COMMENT=	find assets from cloud providers

MODGO_MODNAME=	github.com/projectdiscovery/cloudlist
MODGO_VERSION=	v1.0.3

DISTNAME=	cloudlist-${MODGO_VERSION}

CATEGORIES=	security

HOMEPAGE=	https://github.com/projectdiscovery/cloudlist

MAINTAINER= 	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+= 	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>

