COMMENT=		javascript code obfuscator

DISTNAME=		jsobfu-0.4.2
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/jsobfu

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rkelly-remix

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
