COMMENT=	phishing toolkit

MODGO_MODNAME=	github.com/gophish/gophish
MODGO_VERSION=	v0.12.1

DISTNAME=	Gophish-${MODGO_VERSION}
PKGNAME=	gophish-0.12.1

CATEGORIES=	security

HOMEPAGE=	https://getgophish.com

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
