COMMENT=		JSON implementation as a Ruby extension in C

DISTNAME=		json-2.6.3
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Ruby
PERMIT_PACKAGE=		Yes

WANTLIB+=		c m

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
