COMMENT=		Ruby Exploitation Rex lib for zip files

DISTNAME=		rex-zip-0.1.4
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-socket

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rex-text

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
