COMMENT=		ascii85 methods

DISTNAME=		Ascii85-1.1.0
PKGNAME=		ascii85-1.1.0

CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>