COMMENT=		Java serializer parser for Ruby

DISTNAME=		rex-java-0.1.6
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-java

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Unlicense
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
