COMMENT=	utility for service discovery

MODGO_MODNAME=	github.com/praetorian-inc/fingerprintx
MODGO_VERSION=	v1.1.9

DISTNAME=	fingerprintx-${MODGO_VERSION}
PKGNAME=	fingerprintx-1.1.9

CATEGORIES=	security

HOMEPAGE=	https://github.com/praetorian-inc/fingerprintx

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# Apache 2.0
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
