COMMENT=	DNS wordlists through permutations

MODGO_MODNAME=	github.com/Josue87/gotator
MODGO_VERSION=	v0.0.0-20220531210547-85554801a28a

DISTNAME=	gotator-${MODGO_VERSION}
PKGNAME=	gotator-1.1

CATEGORIES=	security

HOMEPAGE=	https://github.com/Josue87/gotator

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# GPL-3.0
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include <bsd.port.mk>
