COMMENT=		monospace display width

DISTNAME=		unicode-display_width-2.4.2
PKGNAME=		unicode-display-width-2.4.2
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
