COMMENT=		css parser

DISTNAME=		crass-1.0.6
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rgrove/crass

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
