COMMENT=		rails internals

DISTNAME=		railties-7.0.4.3
CATEGORIES=		devel

HOMEPAGE=		https://rubyonrails.org

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-actionpack \
			devel/ruby-activesupport \
			devel/ruby-method-source \
			devel/ruby-thor \
			devel/ruby-zeitwerk

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
