COMMENT=		core libraries for Ruby Exploitation Suite

DISTNAME=		rex-core-0.1.31
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-core

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
