COMMENT=		PDF parser lib for Ruby

DISTNAME=		pdf-reader-2.11.0
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-afm \
			devel/ruby-ascii85 \
			devel/ruby-hashery \
			devel/ruby-rc4 \
			devel/ruby-ttfunk

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
