COMMENT=		MIME parser

DISTNAME=		rex-mime-0.1.7
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-mime

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rex-text

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
