COMMENT=		faraday retry

DISTNAME=		faraday-retry-2.1.0
CATEGORIES=		devel
MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS}
RUN_DEPENDS+=		devel/ruby-faraday

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
