COMMENT=		faraday retry

DISTNAME=		faraday-retry-2.2.0
CATEGORIES=		devel

HOMEPAGE=		https://github.com/lostisland/faraday-retry

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-faraday,${MODRUBY_FLAVOR}

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
