COMMENT=		memory profiling routines for Ruby 2.5+

DISTNAME=		memory_profiler-1.0.1
PKGNAME=		memory-profiler-1.0.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
