COMMENT=		fast, safe and extensible Markdown to (X)HTML parser

DISTNAME=		redcarpet-3.6.0

CATEGORIES=		textproc

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem ext

TEST_DEPENDS=		${FULLPKGNAME}:${BUILD_PKGPATH}
MODRUBY_TEST=		ruby

SUBST_VARS=		RUBY

.include <bsd.port.mk>
