COMMENT =		library for work with CouchDB

MODPY_EGG_VERSION = 	1.0
DISTNAME =  		CouchDB-${MODPY_EGG_VERSION}
PKGNAME =  		py-${DISTNAME}

CATEGORIES =  		devel

# BSD
PERMIT_PACKAGE = 	Yes

MODULES =  		lang/python

MODPY_PI =  		Yes
MODPY_SETUPTOOLS = 	Yes

FLAVORS =  		python3
FLAVOR ?=		python3

.include <bsd.port.mk>
