COMMENT=		boot large ruby rails

DISTNAME=		bootsnap-1.16.0
CATEGORIES=		devel

HOMEPAGE=		https://github.com/Shopify/bootsnap

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			net/ruby-msgpack

CONFIGURE_STYLE=	ruby gem ext

.include <bsd.port.mk>
