COMMENT=		generate private/public SSH keypairs for Ruby

DISTNAME=		sshkey-2.0.0
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
