COMMENT=		decoration for backoff

MODPY_EGG_VERSION=	2.2.1

DISTNAME=		backoff-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/litl/backoff

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=	lang/python

FLAVORS=	python3
FLAVOR=		python3

MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

NO_TEST=	Yes

.include <bsd.port.mk>
