COMMENT=		aws based signer

DISTNAME=		aws-sigv4-1.5.2
CATEGORIES=		devel

HOMEPAGE=		https://github.com/aws/aws-sdk-ruby

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Apache 2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-aws-eventstream

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
