COMMENT=	analysis and xss scanner

MODGO_MODNAME=	github.com/hahwul/dalfox/v2
MODGO_VERSION=	v2.9.1

DISTNAME=	dalfox-${MODGO_VERSION}
PKGNAME=	dalfox-2.9.1

CATEGORIES=	security

HOMEPAGE=	https://github.com/hahwul/dalfox

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
