COMMENT=		jmespath for Ruby

DISTNAME=		jmespath-1.6.2
CATEGORIES=		devel

HOMEPAGE=		http://github.com/trevorrowe/jmespath.rb

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Apache 2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
