COMMENT=		bindata

DISTNAME=		bindata-2.4.15
CATEGORIES=		devel

HOMEPAGE=		https://github.com/dmendel/bindata

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-2-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
