COMMENT=		levenshtein C extension module

MODPY_EGG_VERSION=	0.20.5
DISTNAME=		python-Levenshtein-${MODPY_EGG_VERSION}
PKGNAME=		py-levenshtein-${MODPY_EGG_VERSION}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/maxbachmann/python-Levenshtein

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# GPL-2.0
PERMIT_PACKAGE=		Yes

GH_ACCOUNT=	maxbachmann
GH_PROJECT=	python-Levenshtein
GH_TAGNAME=	v${MODPY_EGG_VERSION}

MODULES=	lang/python

FLAVORS=	python3
FLAVOR=		python3

MODPY_PYBUILD=	setuptools

.include <bsd.port.mk>
