     SUBDIR =
     SUBDIR += dbus
     SUBDIR += gnome
     SUBDIR += gtk+2
     SUBDIR += gtk+3
     SUBDIR += gtk+4
     SUBDIR += hicolor-icon-theme
     SUBDIR += libhandy
     SUBDIR += py-xcbgen,python3
     SUBDIR += qt5
     SUBDIR += tk
     SUBDIR += xkbcommon

.include <bsd.port.subdir.mk>
