COMMENT=		option groups missing in Click

MODPY_EGG_VERSION=	0.5.6
DISTNAME=		click-option-group-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}
CATEGORIES=		devel

HOMEPAGE=		https://github.com/click-contrib/click-option-group

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD 3-Clause
PERMIT_PACKAGE=		Yes

MODPY_PI=		Yes
MODPY_PYBUILD=		setuptools

MODULES=		lang/python
FLAVORS=		python3
FLAVOR=			python3

.include <bsd.port.mk>
