COMMENT=	cloud enumerator

MODGO_MODNAME=	github.com/0xsha/cloudbrute
MODGO_VERSION=	v1.0.7

DISTNAME=	cloudbrute-${MODGO_VERSION}

CATEGORIES=	security

HOMEPAGE=	https://github.com/0xsha/cloudbrute

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+= 	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
