COMMENT=	wayback machine tool

MODGO_MODNAME=	github.com/tomnomnom/waybackurls
MODGO_VERSION=	v0.1.0

DISTNAME=	waybackurls-${MODGO_VERSION}
PKGNAME=	waybackurls-0.1.0

CATEGORIES=	security

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# Unlicense
PERMIT_PACKAGE=	Yes

WANTLIB+= 	c pthread

MODULES=	lang/go

.include <bsd.port.mk>
