COMMENT=		pure Ruby DNS client

DISTNAME=		dnsruby-1.70.0
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Apache-2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-simpleidn

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
