     SUBDIR =
     SUBDIR += chronos
     SUBDIR += photon
     SUBDIR += recong-ng
     SUBDIR += sherlock
     SUBDIR += sn0int
     SUBDIR += spiderfoot
     SUBDIR += theharvester

.include <bsd.port.subdir.mk>
