COMMENT=		subclass for handling dates

DISTNAME=		date-3.3.3
CATEGORIES=		devel

HOMEPAGE=		https://github.com/ruby/date

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-2-Clause
PERMIT_PACKAGE=		Yes

WANTLIB +=		c m

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
