COMMENT=		opty2 library for dynamic generation

DISTNAME=		rex-nop-0.1.2
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-nop

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rex-arch

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
