COMMENT=		ruby framework for Behaviour Driven Development
V=			3.12.0
DISTNAME=		rspec-$V

BUILD_DEPENDS=		${RUN_DEPENDS} \
	 		devel/ruby-rspec/3/core \
			devel/ruby-rspec/3/expectations \
			devel/ruby-rspec/3/mocks

.include <bsd.port.mk>
