COMMENT=		binding to Ed25519 elliptic curve public-key

DISTNAME=		ed25519-1.3.0
CATEGORIES=		devel

HOMEPAGE=		https://github.com/RubyCrypto/ed25519

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

WANTLIB+=		c m

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
