     SUBDIR =
     SUBDIR += leafpad
     SUBDIR += vim,gtk3
     SUBDIR += vim,gtk3,lua
     SUBDIR += vim,gtk3,perl,python3,ruby
     SUBDIR += vim,gtk3,python3
     SUBDIR += vim,no_x11
     SUBDIR += vim,no_x11,lua
     SUBDIR += vim,no_x11,perl,python3,ruby
     SUBDIR += vim,no_x11,python3

.include <bsd.port.subdir.mk>
