COMMENT=		Ruby SSH 2.0 server and client implementation

DISTNAME=		hrr_rb_ssh-0.4.2
PKGNAME=		hrr-rb-ssh-0.4.2
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Apache-2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
