COMMENT=		domain lib

DISTNAME=		domain_name-0.5.20190701
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-2-Clause, BSD-3-Clause, MPL-2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-unf

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
