COMMENT=		clipboard module for Python

MODPY_EGG_VERSION=	1.8.2
DISTNAME=		pyperclip-${MODPY_EGG_VERSION}
PKGNAME=		py-perclip-${MODPY_EGG_VERSION}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/asweigart/pyperclip

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

HOMEPAGE=		https://github.com/asweigart/pyperclip

# BSD
PERMIT_PACKAGE=		Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_PYBUILD=		setuptools

FLAVORS=		python3
FLAVOR=			python3

.include <bsd.port.mk>