COMMENT=		Ruby library to create XML markup and data structures

DISTNAME=		builder-3.2.4
CATEGORIES=		textproc

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

MODRUBY_TEST=		rake
MODRUBY_TEST_TARGET=	-I lib test_all

.include <bsd.port.mk>
