     SUBDIR =
     SUBDIR += blas
     SUBDIR += cblas
     SUBDIR += double-conversion
     SUBDIR += lapack
     SUBDIR += py-networkx,python3
     SUBDIR += py-numpy,python3
     SUBDIR += py-oldest-supported-numpy,python3
     SUBDIR += py-pandas,python3

.include <bsd.port.subdir.mk>
