COMMENT =	parallel HTTP requests

DISTNAME =	typhoeus-1.4.0

CATEGORIES =	www
HOMEPAGE =	https://github.com/typhoeus/typhoeus

MAINTAINER =	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =	lang/ruby

CONFIGURE_STYLE =	ruby gem

BUILD_DEPENDS =	${RUN_DEPENDS}
RUN_DEPENDS =	www/ruby-ethon,${MODRUBY_FLAVOR}

NO_TEST = Yes

.include <bsd.port.mk>
