COMMENT=		stack manipulation routines

DISTNAME=		rex-arch-0.1.14
CATEGORIES=		devel
MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rex-text

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
