COMMENT=		file support for asyncio

MODPY_EGG_VERSION=	23.1.0

DISTNAME=		aiofiles-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		net

HOMEPAGE=		https://github.com/Tinche/aiofiles

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Apache-2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/python
MODPY_PI=		Yes
MODPY_PYBUILD=		setuptools

FLAVORS=		python3
FLAVOR=			python3

NO_TEST=		Yes

.include <bsd.port.mk>
