COMMENT=		pure-ruby implementation of the SSH2 client protocol

DISTNAME=		net-ssh-7.1.0
CATEGORIES=		net

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

MODRUBY_TEST=		rake

.include <bsd.port.mk>
