COMMENT=		Ruby documentation tool

DISTNAME=		yard-0.9.34
CATEGORIES=		textproc

HOMEPAGE=		http://yardoc.org/

# BSD
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

RUN_DEPENDS=		devel/ruby-webrick

.include <bsd.port.mk>
