COMMENT=		security headers

MODPY_EGG_VERSION=	0.3.0
DISTNAME=		secure-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		security

HOMEPAGE=		https://github.com/cak/secure

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

GH_ACCOUNT=		cak
GH_PROJECT=		secure
GH_COMMIT=		04dd035e560583baeba06f5714f273b542c07767

MODULES=		lang/python

MODPY_PYBUILD=		setuptools

.include <bsd.port.mk>
