COMMENT=		wrapper to convert hmtl to pdf

MODPY_EGG_VERSION=	1.0.0

DISTNAME=		pdfkit-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/JazzCore/python-pdfkit

# MIT
PERMIT_PACKAGE=		Yes

MODULES=	lang/python
MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

FLAVORS=	python3
FLAVOR=		python3

NO_TEST=	Yes

.include <bsd.port.mk>
