COMMENT=		mid-level packet manipulation lib

DISTNAME=		packetfu-1.1.13
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-pcaprub

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
