COMMENT=		string matching library

DISTNAME=		mustermann-3.0.0
CATEGORIES=		www

HOMEPAGE=		https://github.com/sinatra/mustermann

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS= 		${RUN_DEPENDS} \
			devel/ruby-ruby2-keywords


CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
