COMMENT=		factory bot rails

DISTNAME=		factory_bot_rails-6.2.0
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-factory-bot \
			devel/ruby-railties

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
