COMMENT=		faker for ruby

DISTNAME=		faker-3.2.0
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-i18n

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
