COMMENT=		ROP chains builder for Ruby

DISTNAME=		rex-rop_builder-0.1.4
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-rop_builder

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-metasm \
			devel/ruby-rex-core \
			devel/ruby-rex-text

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
