COMMENT=		rex socket abstraction library

DISTNAME=		rex-socket-0.1.51
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-socket

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rex-core

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
