COMMENT=		Ruby NTLM authentication

DISTNAME=		rubyntlm-0.6.3
CATEGORIES=		devel
MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
