COMMENT=		XDR Helper Library

DISTNAME=		xdr-3.0.3
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Apache-2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-activemodel \
			devel/ruby-activesupport

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
