COMMENT=		rspec expectations and matchers
DISTNAME=		rspec-expectations-3.12.3

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-diff-lcs,${MODRUBY_FLAVOR} \
			devel/ruby-rspec/3/support,${MODRUBY_FLAVOR}

.include <bsd.port.mk>
