COMMENT=		timeout for Ruby

DISTNAME=		timeout-0.4.0
CATEGORIES=		devel

HOMEPAGE=		https://github.com/ruby/timeout

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-2-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
