     SUBDIR =
     SUBDIR += cdparanoia
     SUBDIR += flac
     SUBDIR += gsm
     SUBDIR += ladspa
     SUBDIR += lame
     SUBDIR += libbs2b
     SUBDIR += libid3tag
     SUBDIR += libogg
     SUBDIR += libsamplerate
     SUBDIR += libsndfile
     SUBDIR += libvorbis
     SUBDIR += opus
     SUBDIR += soundtouch
     SUBDIR += speex
     SUBDIR += speexdsp
     SUBDIR += taglib
     SUBDIR += twolame
     SUBDIR += wavpack
 
.include <bsd.port.subdir.mk>
