     SUBDIR =
     SUBDIR += brotli
     SUBDIR += bzip2
     SUBDIR += gtar
     SUBDIR += libarchive
     SUBDIR += lz4
     SUBDIR += lzo2
     SUBDIR += snappy
     SUBDIR += unzip
     SUBDIR += unzip,iconv
     SUBDIR += woff2
     SUBDIR += xz
     SUBDIR += zip
     SUBDIR += zstd

.include <bsd.port.subdir.mk>
