COMMENT=		flexible plugin for python

MODPY_EGG_VERSION=	1.0.0
DISTNAME=		pluginbase-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/mitsuhiko/pluginbase

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD
PERMIT_PACKAGE=	Yes

GH_ACCOUNT=		mitsuhiko
GH_PROJECT=		pluginbase
GH_TAGNAME=		${MODPY_EGG_VERSION}

MODULES=		lang/python

MODPY_PYBUILD=		setuptools

.include <bsd.port.mk>
