COMMENT=		Ruby lib for random identifier strings

DISTNAME=		rex-random_identifier-0.1.10
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-random_identifier

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rex-text

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
