COMMENT=		database queries constructor

DISTNAME=		arel-helpers-2.14.0
CATEGORIES=		devel

HOMEPAGE=		https://github.com/camertron/arel-helpers

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-activerecord,${MODRUBY_FLAVOR}

CONFIGURE_STYLE=	ruby gem ext

.include <bsd.port.mk>
