COMMENT=		rubocop node pattern classes

DISTNAME=		rubocop-ast-1.28.0
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-parser,${MODRUBY_FLAVOR}

CONFIGURE_STYLE = 	ruby gem

.include <bsd.port.mk>
