     SUBDIR =
     SUBDIR += db
     SUBDIR += freetds
     SUBDIR += gdbm
     SUBDIR += iodbc
     SUBDIR += mariadb
     SUBDIR += openldap
     SUBDIR += openldap,aci
     SUBDIR += openldap,aci,gssapi
     SUBDIR += openldap,gssapi
     SUBDIR += postgresql
     SUBDIR += postgresql-previous
     SUBDIR += py-ldap,python3
     SUBDIR += py-mongo,python3
     SUBDIR += py-mmsql,python3
     SUBDIR += sqlite3
     SUBDIR += tdb

.include <bsd.port.subdir.mk>
