COMMENT=	standard multiprocessing module

MODPY_EGG_VERSION=	0.9.0

DISTNAME=	aiomultiprocess-${MODPY_EGG_VERSION}
PKGNAME=	py-${DISTNAME}

CATEGORIES=	net

HOMEPAGE=	https://pypi.org/project/aiomultiprocess

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

MODULES=	lang/python
MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

FLAVORS=	python3
FLAVOR=		python3

NO_TEST=	Yes

.include <bsd.port.mk>
