COMMENT=	IPv4/IPv6 manipulation library

MODPY_EGG_VERSION=	1.0.19

DISTNAME=	ipaddress-${MODPY_EGG_VERSION}
PKGNAME=	py-${DISTNAME}

CATEGORIES=	devel

HOMEPAGE=	https://github.com/phihag/ipaddress

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# PSF-2.0
PERMIT_PACKAGE=	Yes

MODULES=	lang/python

FLAVORS=	python3
FLAVOR=		python3

MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

.include <bsd.port.mk>
