COMMENT=		read exif metadata from tiff and jpeg files

MODPY_EGG_VERSION=	3.0.0

DISTNAME=		exifread-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/ianare/exif-py

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD
PERMIT_PACKAGE=		Yes

GH_ACCOUNT=		ianare
GH_PROJECT=		exif-py
GH_TAGNAME=		${MODPY_EGG_VERSION}

MODULES=		lang/python

MODPY_PYBUILD=		setuptools

.include <bsd.port.mk>
