COMMENT=		file size handler class

DISTNAME=		filesize-0.2.0
CATEGORIES=		devel
	
MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
