     SUBDIR =
     SUBDIR += font-awesome
     SUBDIR += hermit-font
     SUBDIR += nerd-fonts
     SUBDIR += noto
     SUBDIR += spleen
     SUBDIR += terminus-font
     SUBDIR += terminus-font,centered_tilde
     SUBDIR += terminus-font,symquotes
     SUBDIR += terminus-font,symquotes,centered_tilde

.include <bsd.port.subdir.mk>
