COMMENT=		tests profiling tools

DISTNAME=		test-prof-1.2.2
CATEGORIES=		devel

HOMEPAGE=		https://test-prof.evilmartians.io	

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
