COMMENT=		LALR parser generator

DISTNAME=		racc-1.6.2
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Ruby
PERMIT_PACKAGE=		Yes

WANTLIB+=		c m

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
