COMMENT=		rspec stubbing and mocking
DISTNAME=		rspec-mocks-3.12.5

BUILD_DEPENDS=	 	${RUN_DEPENDS} \
			devel/ruby-diff-lcs,${MODRUBY_FLAVOR} \
			devel/ruby-rspec/3/support,${MODRUBY_FLAVOR}

.include <bsd.port.mk>
