COMMENT=		activemodel

DISTNAME=		activemodel-7.0.4.3
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-activesupport

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
