COMMENT=		bcrypt_pbkdf implements

DISTNAME=		bcrypt_pbkdf-1.1.0
CATEGORIES=		devel

HOMEPAGE=		https://github.com/net-ssh/bcrypt_pbkdf-ruby

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

WANTLIB+=		c m

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
