COMMENT=		generate gexf file format

MODPY_EGG_VERSION=	0.2.2
DISTNAME=		pygexf-${MODPY_EGG_VERSION}
PKGNAME=		py-gexf-${MODPY_EGG_VERSION}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/paulgirard/pygexf

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# GPL-3.0 
PERMIT_PACKAGE=		Yes

GH_ACCOUNT=		paulgirard
GH_PROJECT=		pygexf
GH_TAGNAME=		v${MODPY_EGG_VERSION}

MODULES=		lang/python

MODPY_PYBUILD=		setuptools

FLAVOR=			python3
FLAVORS=		python3

.include <bsd.port.mk>
