COMMENT=	base64 encoder decoder

DISTNAME=	base64-0.1.1
CATEGORIES=	devel

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# BSD-2-Clause
PERMIT_PACKAGE=	Yes

CONFIGURE_STYLE=	gem

MODULES=	lang/ruby

.include <bsd.port.mk>