COMMENT=		code loader

V=			3.0.0
DISTNAME=		require_all-${V}
PKGNAME=		require-all-${V}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/jarmo/require_all

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
