COMMENT =	sanitize HTML fragments

DISTNAME =	rails-html-sanitizer-1.5.0
CATEGORIES =	devel
MAINTAINER =	Purple Rain <purplerain@secbsd.org>
REVISION =	0

HOMEPAGE =	https://github.com/rails/rails-html-sanitizer

# MIT
PERMIT_PACKAGE =Yes

MODULES =	lang/ruby

BUILD_DEPENDS =	${RUN_DEPENDS}
RUN_DEPENDS =	devel/ruby-loofah

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
