COMMENT=		sanitize HTML fragments

DISTNAME=		rails-html-sanitizer-1.6.0

CATEGORIES=		devel

HOMEPAGE=		https://github.com/rails/rails-html-sanitizer

MAINTAINER=             Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-loofah,${MODRUBY_FLAVOR}

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
