COMMENT=	information gathering tool

V=	1.2.7
MODGO_MODNAME=	github.com/edoardottt/scilla
MODGO_VERSION=	v${V}

DISTNAME=	scilla-${MODGO_VERSION}
PKGNAME=	scilla-${V}

CATEGORIES=	security

HOMEPAGE=	https://github.com/edoardottt/scilla

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
