COMMENT=		scripting for custom ASCII

MODPY_EGG_VERSION=	1.0.0
DISTNAME=		py-colorscript-${MODPY_EGG_VERSION}

CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

HOMEPAGE=		https://github.com/EntySec/ColorScript

# MIT
PERMIT_PACKAGE=		Yes

GH_ACCOUNT=		EntySec
GH_PROJECT=		ColorScript
GH_COMMIT=		b6f59d4e068832e60d52960d898186ed2d63a5b6

MODULES=		lang/python

MODPY_PYBUILD=		setuptools

FLAVOR=			python3
FLAVORS=		python3

.include <bsd.port.mk>
