COMMENT=	PostgreSQL database interface for ruby

DISTNAME=	pg-1.4.6

CATEGORIES=	databases

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# BSD-2-Clause
PERMIT_PACKAGE=	Yes

MODULES=	lang/ruby

WANTLIB=	c++abi pq
LIB_DEPENDS=	databases/postgresql

CONFIGURE_STYLE= ruby gem ext

.include <bsd.port.mk>
