COMMENT=		SSLScan tool implementation for Ruby

DISTNAME=		rex-sslscan-0.1.9
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-sslscan

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rex-core \
			devel/ruby-rex-socket \
			devel/ruby-rex-text

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
