COMMENT=		cross platform mac address determiniation

DISTNAME=		macaddr-1.7.2
CATEGORIES=		net

HOMEPAGE=		https://github.com/ahoward/macaddr/

# ruby
PERMIT_PACKAGE=	Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	gem

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-systemu,${MODRUBY_FLAVOR}

.include <bsd.port.mk>
