COMMENT=		MySQL connector for Ruby

DISTNAME=		ruby-mysql-4.0.0
CATEGORIES=		databases

HOMEPAGE=		https://gitlab.com/tmtms/ruby-mysql

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
