COMMENT=		metasploit payloads

DISTNAME=		metasploit-payloads-2.0.130
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
