COMMENT=		re-run failed RSpec tests

DISTNAME=		rspec-rerun-1.1.0
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-rspec/3/rspec

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
