COMMENT=		cookie handler for Ruby

DISTNAME=		http-cookie-1.0.5
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-domain-name

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
