COMMENT=		strings to unicode

DISTNAME=		simpleidn-0.2.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-unf,${MODRUBY_FLAVOR}

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
