COMMENT=		web attack rack protection

DISTNAME=		rack-protection-3.0.6
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			www/ruby-rack

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
