COMMENT=		secret user agent of HTTP

DISTNAME=		sawyer-0.9.2
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			www/ruby-addressable \
			devel/ruby-faraday

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
