COMMENT=		simple wrapper for the GitHub API

DISTNAME=		octokit-4.25.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-faraday \
			devel/ruby-sawyer

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
