COMMENT=		LDAP for Ruby

DISTNAME=		net-ldap-0.18.0
CATEGORIES=		net

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
