COMMENT=		fingerprints scanner

DISTNAME=		recog-3.1.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Unlicense
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			textproc/ruby-nokogiri

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
