COMMENT=		bson for Ruby

DISTNAME=		bson-4.15.0
CATEGORIES=		devel

HOMEPAGE=		https://docs.mongodb.com/ruby-driver/current/tutorials/bson-v4

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Apache 2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem ext

.include <bsd.port.mk>
