COMMENT=		ASN lib for Ruby

DISTNAME=		rasn1-0.12.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-strptime

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
