COMMENT=		ruby2 keywords

DISTNAME=		ruby2_keywords-0.0.5
CATEGORIES=		devel

HOMEPAGE=		https://github.com/ruby/ruby2_keywords

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-2-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
