COMMENT=		metasploit model

DISTNAME=		metasploit-model-5.0.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Unlicense
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-activemodel \
			devel/ruby-activesupport \
			devel/ruby-railties

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
