COMMENT=		customizable vulnerability scanner

MODGO_MODNAME=		github.com/projectdiscovery/nuclei/v3
MODGO_VERSION=		v3.3.1

DISTNAME=		nuclei-${MODGO_VERSION}

CATEGORIES=		security

HOMEPAGE=		https://projectdiscovery.io

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

WANTLIB+=		c pthread

MODULES=		lang/go

.include "modules.inc"

.include <bsd.port.mk>
