COMMENT=		powershell scripts generator for Ruby

DISTNAME=		rex-powershell-0.1.97
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-powershell

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-rex-random-identifier \
			devel/ruby-rex-text \
			devel/ruby-rc4

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
