COMMENT=		logging lib for Ruby

DISTNAME=		logging-2.3.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-little-plugger \
			converters/ruby-multi-json

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
