COMMENT=		small, simple testing API for Rack apps

DISTNAME=		rack-test-2.1.0
CATEGORIES=		www

HOMEPAGE=		https://github.com/brynary/rack-test

# MIT
PERMIT_PACKAGE=	Yes

MODULES=		lang/ruby

BUILD_DEPENDS =		${RUN_DEPENDS}
RUN_DEPENDS =		www/ruby-rack

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
