COMMENT=	multi-purpose HTTP toolkit

MODGO_MODNAME=	github.com/projectdiscovery/httpx
MODGO_VERSION=	v1.6.3

DISTNAME=	httpx-${MODGO_VERSION}

CATEGORIES=	security

HOMEPAGE=	https://github.com/projectdiscovery/httpx

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
