COMMENT=		factory bot

DISTNAME=		factory_bot-6.2.1
PKGNAME=		factory-bot-6.2.1
CATEGORIES=		devel
MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-activesupport

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
