COMMENT=		rkelly javascript parser

DISTNAME=		rkelly-remix-0.0.7
CATEGORIES=		devel

HOMEPAGE=		https://github.com/nene/rkelly-remix

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
