     SUBDIR =
     SUBDIR += cython,python3
     SUBDIR += duktape
     SUBDIR += gcc
     SUBDIR += go
     SUBDIR += guile
     SUBDIR += lua
     SUBDIR += node
     SUBDIR += python
     SUBDIR += rust
     SUBDIR += solidity
     SUBDIR += tcl

.include <bsd.port.subdir.mk>
