COMMENT=		transparent proxy for eventmachine

DISTNAME=		em-socksify-0.3.2
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-eventmachine

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
