COMMENT=		Ruby exploitation rex methods

DISTNAME=		rex-text-0.2.52
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-text

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
