COMMENT=		SMTP for Ruby

DISTNAME=		net-smtp-0.3.3
CATEGORIES=		net

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Ruby, BSD-2-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			net/ruby-net-protocol

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
