COMMENT=		parser

DISTNAME=		public_suffix-5.0.1
CATEGORIES=		net

HOMEPAGE=		https://simonecarletti.com/code/publicsuffix-ruby

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Apache 2.0
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem ext

.include <bsd.port.mk>
