COMMENT=	creates NTLM authentication structures

MODPY_EGG_VERSION=	1.5.0
DISTNAME=	ntlm-auth-${MODPY_EGG_VERSION}
PKGNAME=	py-${DISTNAME}

CATEGORIES=	security

HOMEPAGE=	https://github.com/jborean93/ntlm-auth

# MIT
PERMIT_PACKAGE=	Yes

GH_ACCOUNT=	jborean93
GH_PROJECT=	ntlm-auth
GH_TAGNAME=	v${MODPY_EGG_VERSION}

MODULES=	lang/python

MODPY_PYBUILD=	setuptools

FLAVORS=	python3
FLAVOR?=	python3

.include <bsd.port.mk>
