COMMENT=		ruby command-line tool for REPL

DISTNAME=		irb-1.6.4
CATEGORIES=		devel
MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Ruby, BSD-2-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-reline

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
