COMMENT=		libpcap bindings for Ruby 2.x

DISTNAME=		pcaprub-0.13.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# LGPL-2.1
PERMIT_PACKAGE=		Yes

WANTLIB+=		c m pcap

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
