COMMENT=		color uncaught exception tracebacks

MODPY_EGG_VERSION=	0.3.0
DISTNAME=		colored-traceback-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/staticshock/colored-traceback.py

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# ISC
PERMIT_PACKAGE=		Yes

MODULES=		lang/python

FLAVORS=		python3
FLAVOR=			python3

MODPY_PI=		Yes
MODPY_PYBUILD=		setuptools

.include <bsd.port.mk>
