COMMENT=		 functions for validating data

MODPY_EGG_VERSION=	1.5.0
DISTNAME=		validator-collection-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		devel

HOMEPAGE=		https://validator-collection.readthedocs.io/en/latest/index.html

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES =		lang/python

FLAVORS=		python3
FLAVOR=			python3

MODPY_PI=		Yes
MODPY_PYBUILD=		setuptools

.include <bsd.port.mk>
