COMMENT=		parser

DISTNAME=		http_parser.rb-0.8.0
PKGNAME=		http-parser-0.8.0

CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

WANTLIB+=		c m

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
