COMMENT=		Ruby Gem for RFC 4493, 4494, 4615

DISTNAME=		openssl-cmac-2.0.2
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
