COMMENT=		faraday

DISTNAME=		faraday-2.7.4
CATEGORIES=		devel
MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-faraday-net-http \
			devel/ruby-ruby2-keywords

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
