COMMENT=		asyncio bridge to sqlite3 module

MODPY_EGG_VERSION=	0.19.0

DISTNAME=		aiosqlite-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		net

HOMEPAGE=		https://github.com/omnilib/aiosqlite

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=	lang/python
MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

FLAVORS=	python3
FLAVOR=		python3

NO_TEST=	Yes

.include <bsd.port.mk>
