COMMENT=		parser for Adblock Plus rules

MODPY_EGG_VERSION=	0.7
DISTNAME=		adblockparser-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		devel

HOMEPAGE=		https://github.com/scrapinghub/adblockparser

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

GH_ACCOUNT=		scrapinghub
GH_PROJECT=		adblockparser
GH_COMMIT=		4089612d65018d38dbb88dd7f697bcb07814014d

MODULES=		lang/python

FLAVORS=		python3
FLAVOR=			python3

MODPY_PYBUILD=		setuptools

.include <bsd.port.mk>
