COMMENT=		gem for tokenizing, parsing, and transforming regexps

DISTNAME=		regexp_parser-2.8.0
CATEGORIES=		devel

HOMEPAGE=		https://github.com/ammar/regexp_parser

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
