COMMENT=		ASGI server

MODPY_EGG_VERSION=	0.22.0

DISTNAME=		uvicorn-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		net

HOMEPAGE=		https://www.uvicorn.org

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD
PERMIT_PACKAGE=		Yes

MODULES=		lang/python

FLAVORS=		python3
FLAVOR=			python3

MODPY_PI=		Yes
MODPY_PYBUILD=		setuptools

.include <bsd.port.mk>
