COMMENT=		UNF support for CRuby

DISTNAME=		unf_ext-0.0.8.2
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

WANTLIB+=		${COMPILER_LIBCXX} c m

MODULES=		lang/ruby

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
