COMMENT=	spidering framework

MODGO_MODNAME=	github.com/projectdiscovery/katana
MODGO_VERSION=	v1.0.3

DISTNAME=	katana-${MODGO_VERSION}
PKGNAME=	katana-1.0.3

CATEGORIES=	security

HOMEPAGE=	https://github.com/projectdiscovery/katana

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
