COMMENT=		cross-architecture assembler disassembler

DISTNAME=		metasm-1.0.5
CATEGORIES=		devel

HOMEPAGE=		https://www.cr0.org/progs/metasm

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# LGPL v2.1
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
