COMMENT=	extract tool from JS code

MODGO_MODNAME=	github.com/BishopFox/jsluice
MODGO_VERSION=	v0.0.0-20230629150035-2c4584eded5a

DISTNAME=	jsluice-${MODGO_VERSION}
PKGNAME=	jsluice-0.0.1

CATEGORIES=	security

HOMEPAGE=	https://github.com/BishopFox/jsluice	

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+= 	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
