MODGO_MODULES =	\
	github.com/davecgh/go-spew		 v1.1.1 \
	github.com/google/go-cmp		 v0.5.8 \
	github.com/pkg/profile			 v1.6.0 \
	github.com/pmezard/go-difflib		 v1.0.0 \
	github.com/smacker/go-tree-sitter	 v0.0.0-20220628134258-ac06e95cfa11 \
	github.com/spf13/pflag			 v1.0.5 \
	github.com/stretchr/objx		 v0.4.0 \
	github.com/stretchr/testify		 v1.7.4 \
	golang.org/x/exp			 v0.0.0-20220706164943-b4a6d9510983 \
	golang.org/x/mod			 v0.6.0-dev.0.20220106191415-9b9b3d81d5e3 \
	golang.org/x/sys			 v0.0.0-20211019181941-9d821ace8654 \
	golang.org/x/tools			 v0.1.10 \
	golang.org/x/xerrors			 v0.0.0-20200804184101-5ec99f83aff1 \
	gopkg.in/check.v1			 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3			 v3.0.1

MODGO_MODFILES =	\
	github.com/davecgh/go-spew	 v1.1.0 \
	github.com/stretchr/objx	 v0.1.0 \
	github.com/stretchr/testify	 v1.7.1 \
	gopkg.in/yaml.v3		 v3.0.0-20200313102051-9f266ea9e77c