COMMENT=		HTML formatter

DISTNAME=		simplecov-html-0.12.3
CATEGORIES=		devel

HOMEPAGE=		https://github.com/simplecov-ruby/simplecov-html

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
