COMMENT=		ruby parser

DISTNAME=		parser-3.2.2.1
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=	 	${RUN_DEPENDS} \
			devel/ruby-ast

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
