     SUBDIR =
     SUBDIR += aom
     SUBDIR += dav1d
     SUBDIR += frei0r-plugins
     SUBDIR += gstreamer1
     SUBDIR += libass
     SUBDIR += libde265
     SUBDIR += libheif
     SUBDIR += libtheora
     SUBDIR += libv4l
     SUBDIR += libvidstab
     SUBDIR += libvpx
     SUBDIR += x264
     SUBDIR += x265
     SUBDIR += xvidcore

.include <bsd.port.subdir.mk>
