COMMENT=		modular Ruby webserver interface

DISTNAME=		rack-2.2.7
CATEGORIES=		www

HOMEPAGE=		http://rack.github.io/

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
