COMMENT=		windows registry parser

DISTNAME=		rex-registry-0.1.4
CATEGORIES=		devel

HOMEPAGE=		https://github.com/rapid7/rex-registry

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# BSD-3-clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
