COMMENT=	SBOMs scanner for security vulnerabilities

MODGO_MODNAME=	github.com/devops-kung-fu/bomber
MODGO_VERSION=	v0.4.4

DISTNAME=	bomber-${MODGO_VERSION}
PKGNAME=	bomber-0.4.4

CATEGORIES=	security

HOMEPAGE=	https://github.com/devops-kung-fu/bomber

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MPL-2.0
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
