COMMENT=	wayback machine OSINT framework 

MODGO_MODNAME=	github.com/mhmdiaa/chronos/v2
MODGO_VERSION=	v2.0.0

DISTNAME=	chronos-${MODGO_VERSION}

CATEGORIES=	osint

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

WANTLIB+=	c pthread

MODULES=	lang/go

.include "modules.inc"

.include <bsd.port.mk>
