COMMENT=		UNF support to Ruby/JRuby

DISTNAME=		unf-0.1.4
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-unf-ext,${MODRUBY_FLAVOR}

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
