COMMENT=	html2text

MODPY_EGG_VERSION=	2020.1.16
DISTNAME=	html2text-${MODPY_EGG_VERSION}
PKGNAME=	py-${DISTNAME}

CATEGORIES =	textproc

HOMEPAGE=	https://github.com/Alir3z4/html2text

# GPL-3.0
PERMIT_PACKAGE=	Yes

MODULES=	lang/python
MODPY_PI=	Yes

MODPY_PYBUILD=	setuptools

FLAVOR=		python3
FLAVORS=	python3

.include <bsd.port.mk>