COMMENT=	extract data from HTML and XML

MODPY_EGG_VERSION=	0.3.2

DISTNAME=	html-similarity-${MODPY_EGG_VERSION}
PKGNAME=	py-${DISTNAME}

CATEGORIES=	devel

HOMEPAGE=	https://github.com/matiskay/html-similarity

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# BSD-3-Clause
PERMIT_PACKAGE=	Yes

RUN_DEPENDS=	devel/py-parsel${MODPY_FLAVOR}

MODULES=	lang/python

FLAVORS=	python3
FLAVOR=		python3

MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

.include <bsd.port.mk>
