COMMENT=		public suffix list for Python

MODPY_EGG_VERSION=	0.9.0
DISTNAME=		publicsuffixlist-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}

CATEGORIES=		net

HOMEPAGE=		https://github.com/ko-zu/psl

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MPL-2.0
PERMIT_PACKAGE=		Yes

GH_ACCOUNT=		ko-zu
GH_PROJECT=		psl
GH_COMMIT=		65ad8723a8707eb177befd4bfb690abdbfc401ae

MODULES=		lang/python

MODPY_PYBUILD=		setuptools

FLAVOR=			python3
FLAVORS=		python3

.include <bsd.port.mk>
