COMMENT=		dom selector

DISTNAME=		rails-dom-testing-2.0.3
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS}
RUN_DEPENDS=		devel/ruby-activesupport \
			textproc/ruby-nokogiri

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
