COMMENT=	language server protocol sdk

V=		3.17.0.3
DISTNAME=	language_server-protocol-${V}
PKGNAME=	language-server-protocol-${V}
CATEGORIES=	devel

MAINTAINER=	Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=	Yes

CONFIGURE_STYLE=	gem

MODULES=	lang/ruby

.include <bsd.port.mk>