COMMENT=		translates Ruby Hashes to XML

DISTNAME=		gyoku-1.4.0
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			textproc/ruby-builder/3.2

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
