COMMENT=		DSL for quickly creating web-applications in Ruby

DISTNAME=		sinatra-3.0.6
CATEGORIES=		www

HOMEPAGE=		http://www.sinatrarb.com

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-tilt \
			www/ruby-mustermann \
			www/ruby-rack \
			devel/ruby-rack-protection

.include <bsd.port.mk>
