COMMENT=		RPC over http

DISTNAME=		xmlrpc-0.3.2
CATEGORIES=		devel

MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS+=		${RUN_DEPENDS} \
			devel/ruby-webrick

CONFIGURE_STYLE= 	ruby gem

.include <bsd.port.mk>
