     SUBDIR =
     SUBDIR += awscli
     SUBDIR += binwalk
     SUBDIR += coreutils
     SUBDIR += flock
     SUBDIR += ggrep
     SUBDIR += libudev-openbsd
     SUBDIR += pciutils
     SUBDIR += polkit
     SUBDIR += py-distlib,python3
     SUBDIR += py-filelock,python3
     SUBDIR += py-packaging,python3
     SUBDIR += py-platformdirs,python3
     SUBDIR += py-psutil,python3
     SUBDIR += xxhash

.include <bsd.port.subdir.mk>
