COMMENT=		interface for net client

DISTNAME=		net-protocol-0.2.1
CATEGORIES=		net
MAINTAINER=		Purple Rain <purplerain@secbsd.org>

# Ruby BSD-2-Clause
PERMIT_PACKAGE=		Yes

MODULES=		lang/ruby

BUILD_DEPENDS=		${RUN_DEPENDS} \
			devel/ruby-timeout \

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
